version: "3.8"

services:
  db:
    build: 
      context: "./db-mysql/."
      args:
        testarg: "test"
    image: "mysql:8.0"
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "jara"
      MYSQL_USER: "django"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "test"

  api:
    build: "./back-api/."
    volumes:
      - "./back-api/:/code"
      - "./front-ui/dist/pwa/:/code/public"
    ports:
      - "8000:8000"
    environment:
      DEBUG: 1
    depends_on:
      - "db"
    command: >
      bash -c "./wait-for-it.sh db:3306 -t 300 -- python manage.py runserver [::]:8000"

  ui:
    build: "./front-ui/."
    volumes:
      - "./front-ui/:/code"
    ports:
      - "8888:8888"
    depends_on:
      - "api"
    command: "yarn run dev"
