version: "3.8"

services:
  db:
    build: "./src-db/."
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "jara"
      MYSQL_USER: "django"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "test"
    command: >
      "--default-authentication-plugin=mysql_native_password"

  api:
    build: "./src-api/."
    volumes:
      - "./src-api/:/code"
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    environment:
      DEBUG: 1
    command: >
      bash -c "
      ./wait-for-it.sh db:3306 -t 300 
      -- python manage.py migrate 
      && python manage.py runserver [::]:8000"

  ui:
    build: "./src-ui/."
    volumes:
      - "./src-ui/:/code"
      - "/code/node_modules"
    ports:
      - "8888:8888"
    depends_on:
      - "api"
    command: >
      yarn dev
