# Generated by Django 4.1 on 2023-10-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='order',
        ),
        migrations.RemoveField(
            model_name='recipeinstruction',
            name='order',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.CharField(blank=True, default=None, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit_of_measure',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='recipeinstruction',
            name='text',
            field=models.CharField(max_length=1024),
        ),
    ]
