# Generated by Django 4.1 on 2023-10-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('first_name', models.CharField(default=None, max_length=45, null=True)),
                ('last_name', models.CharField(default=None, max_length=45, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dt_last_login', models.DateTimeField(default=None, null=True)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
